### ISSUE TITLE
Random Crashes after installing mod

### ISSUE THREAD

**Issue by svenddpc** [Nercury/rimworld-assign-animal-food#1]
Hello :)

Thank you for this mod, it's amazing! I was missing it after updating to 1.5 until I saw the Mod is now compatible today.

However, after installing the mod again, I keep getting random crashes. The crash logs don't seem super useful, but I've included them anyway in case you can spot anything:

[Crash_2024-04-20_062948209.zip](https://github.com/Nercury/rimworld-assign-animal-food/files/15047132/Crash_2024-04-20_062948209.zip)

These are all my enabled mods:

![image](https://github.com/Nercury/rimworld-assign-animal-food/assets/67726143/85ca7631-f625-4c07-9e91-4676b8f1685b)

I can also provide my save game, if that would be helpful.

Let me know if you don't think it's a bug in this mod, but I do believe it's at least related. I've had 5-6 crashes in the last couple of hours, and I've never had crashes like that before (or at least not as far as I remember). I also didn't experience crashes with this mod in 1.4 (and the same in the list plus more, that haven't been updated for 1.5) playing many, many hours.

Cheers,
Svend

**Comment by Nercury** [comment]
Hi, I don't understand what's going on there. The code did not change at all when migrating from 1.4 to 1.5 (besides a rename of FoodRestriction to FoodPolicy). The mod is working on my end.

Nevertheless, I fixed one thing I missed in about file and uploaded 1.5.1 version. But that should not affect anything. 

Try to unsubscribe/subscribe to mod, sometimes steam won't automatically sync to the latest version.

**Comment by svenddpc** [comment]
Thank you for your reply. I tried disabling the mod and I got another crash. I guess that's not what's doing it, and it's just coincidental that they started after I installed the mod... :( I guess I'll have to uninstall all mods and see if it's still happening, to report a Rimworld bug, and if not re-enable them one at a time... It's just very intermittent, so hard to test the cause.
